-- calendar
DROP TABLE IF EXISTS CALENDAR;
CREATE TABLE CALENDAR (
    CALENDAR_DATE DATE NOT NULL,
    WORKDAY ENUM('true', 'false') NOT NULL)
  ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE UNIQUE INDEX CALENDAR_INX ON CALENDAR (CALENDAR_DATE ASC);
--

-- timeoff
DROP TABLE IF EXISTS TIMEOFF;
CREATE TABLE TIMEOFF (
    ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    USER VARCHAR(64) NOT NULL,
    REPORTER VARCHAR(64) NOT NULL,
    DELAYDATE DATE NOT NULL,
    DELAYTIME VARCHAR(5) NOT NULL,
    ABSENT ENUM('true', 'false') NOT NULL,
    COMMENT VARCHAR(4096),
    PRIMARY KEY (ID))
  ENGINE=MyISAM DEFAULT CHARSET=utf8;
--

-- time ons
DROP TABLE IF EXISTS TIMES;
CREATE TABLE TIMES (
    USER VARCHAR(64) NOT NULL,
    TIMEON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)
  ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE UNIQUE INDEX TIMES_INX ON TIMES (USER, TIMEON ASC);
--

-- don't register
DROP TABLE IF EXISTS CANCEL_REGISTER;
CREATE TABLE CANCEL_REGISTER (
    USER VARCHAR(64) NOT NULL,
    TOTIME DATETIME NOT NULL)
  ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE UNIQUE INDEX CANCEL_REGISTER_INX ON CANCEL_REGISTER (USER, TOTIME ASC);
--

-- hr dates
DROP TABLE IF EXISTS HR_DATES;
CREATE TABLE HR_DATES (
    ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    YEAR INT NOT NULL,
    MONTH INT NOT NULL,
    REG_DATE DATE NOT NULL,
    UNIQUE (YEAR, MONTH),
    PRIMARY KEY (ID))
  ENGINE=MyISAM DEFAULT CHARSET=utf8;
--

