package ru.mail.jira.plugins;

/**
 * Sets of SQL queries.
 * 
 * @author andrey
 */
public interface SqlQueries
{
    String ADD_CALENDAR =
        "INSERT INTO CALENDAR (CALENDAR_DATE, WORKDAY) VALUES (?, ?)";

    String ADD_HRDATE =
        "INSERT INTO HR_DATES (YEAR, MONTH, REG_DATE) VALUES (?, ?, ?)";

    String DELETE_HRDATE =
        "DELETE FROM HR_DATES WHERE YEAR = ? AND MONTH = ?";

    String ADD_CANCEL_REG =
        "INSERT INTO CANCEL_REGISTER (USER, TOTIME) VALUES (?, ?);";

    String CHECK_DELAY =
        "SELECT 1 FROM TIMEOFF WHERE USER = ? AND DELAYDATE = ?";

    String DELETE_DELAY =
        "DELETE FROM TIMEOFF WHERE ID = ?";

    String GET_HRDATES =
        "SELECT YEAR, MONTH, REG_DATE FROM HR_DATES ORDER BY YEAR DESC, MONTH DESC";

    String GET_LASTHRDATE =
        "SELECT MAX FROM HR_DATES";

    String GET_HRDATE =
        "SELECT YEAR, MONTH, REG_DATE FROM HR_DATES WHERE YEAR = ? AND MONTH = ?";

    String GET_CALENDAR =
        "SELECT DAY(CALENDAR_DATE), WORKDAY FROM CALENDAR WHERE YEAR(CALENDAR_DATE) = ? AND MONTH(CALENDAR_DATE) = ?";

    String GET_CALENDAR_RANGE =
        "SELECT CALENDAR_DATE, WORKDAY FROM CALENDAR WHERE (CALENDAR_DATE >= ?) AND (CALENDAR_DATE <= ?)";

    String GET_CANCEL_TIME =
        "SELECT TOTIME FROM CANCEL_REGISTER WHERE USER = ? AND TOTIME > NOW();";

    String GET_DELAYS =
        "SELECT ID, USER, REPORTER, DELAYDATE, DELAYTIME, ABSENT, COMMENT FROM TIMEOFF ORDER BY ID";

    String GET_USER_TIMES =
        "SELECT TIMEON FROM TIMES WHERE USER = ? AND DATE(TIMEON) >= ? AND DATE(TIMEON) <= ? ORDER BY TIMEON";

    String REG_TIME_QUERY =
        "SELECT TIMEON FROM TIMES WHERE USER = ? AND TO_DAYS(TIMEON) = TO_DAYS(NOW())";

    String REGISTER_DELAY =
        "INSERT INTO TIMEOFF VALUES (DEFAULT, ?, ?, ?, ?, ?, ?)";

    String REGISTER_TIME =
        "INSERT INTO TIMES (USER, TIMEON) VALUES (?, NOW())";

    String UPDATE_CALENDAR =
        "UPDATE CALENDAR SET WORKDAY = ? WHERE CALENDAR_DATE = ?";

    String WEEK_TIMES_QUERY =
        "SELECT TIMEON FROM TIMES WHERE USER = ? AND YEARWEEK(TIMEON) = YEARWEEK(CURRENT_TIMESTAMP) ORDER BY TIMEON";
}
